-- MySQL Script generated by MySQL Workbench
-- Tue Nov 19 13:52:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema frs_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `frs_db` ;

-- -----------------------------------------------------
-- Schema frs_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `frs_db` DEFAULT CHARACTER SET utf8 ;
USE `frs_db` ;

-- -----------------------------------------------------
-- Table `frs_db`.`fakultas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frs_db`.`fakultas` ;

CREATE TABLE IF NOT EXISTS `frs_db`.`fakultas` (
  `fak_id` INT NOT NULL AUTO_INCREMENT,
  `fak_nama` VARCHAR(45) NOT NULL,
  `fak_deskripsi` VARCHAR(50) NULL,
  PRIMARY KEY (`fak_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frs_db`.`departemen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frs_db`.`departemen` ;

CREATE TABLE IF NOT EXISTS `frs_db`.`departemen` (
  `dep_id` INT NOT NULL AUTO_INCREMENT,
  `dep_nama` VARCHAR(45) NULL,
  `dep_deskripsi` VARCHAR(45) NULL,
  `fakultas_fak_id` INT NOT NULL,
  PRIMARY KEY (`dep_id`),
  INDEX `fk_departemen_fakultas1_idx` (`fakultas_fak_id` ASC),
  CONSTRAINT `fk_departemen_fakultas1`
    FOREIGN KEY (`fakultas_fak_id`)
    REFERENCES `frs_db`.`fakultas` (`fak_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frs_db`.`mahasiswa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frs_db`.`mahasiswa` ;

CREATE TABLE IF NOT EXISTS `frs_db`.`mahasiswa` (
  `mhs_id` INT NOT NULL AUTO_INCREMENT,
  `mhs_departemen` INT NOT NULL,
  `mhs_nim` INT NOT NULL,
  `mhs_nama` VARCHAR(100) NOT NULL,
  `mhs_nohp` VARCHAR(15) NULL,
  `mhs_alamat` VARCHAR(50) NULL,
  `mhs_tahunmasuk` INT NULL,
  `mhs_status` TINYINT(1) NULL,
  `mhs_created` TIMESTAMP NULL,
  `mhs_updated` TIMESTAMP NULL,
  PRIMARY KEY (`mhs_id`),
  INDEX `fk_mahasiswa_departemen1_idx` (`mhs_departemen` ASC),
  CONSTRAINT `fk_mahasiswa_departemen1`
    FOREIGN KEY (`mhs_departemen`)
    REFERENCES `frs_db`.`departemen` (`dep_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frs_db`.`dosen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frs_db`.`dosen` ;

CREATE TABLE IF NOT EXISTS `frs_db`.`dosen` (
  `dos_id` INT NOT NULL AUTO_INCREMENT,
  `dos_nip` INT NOT NULL,
  `dos_nama` VARCHAR(100) NOT NULL,
  `dos_nohp` VARCHAR(15) NULL,
  `dos_alamat` VARCHAR(50) NULL,
  `dos_status` TINYINT(1) NULL,
  `dos_created` TIMESTAMP NULL,
  `dos_updated` TIMESTAMP NULL,
  PRIMARY KEY (`dos_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frs_db`.`dosen_wali`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frs_db`.`dosen_wali` ;

CREATE TABLE IF NOT EXISTS `frs_db`.`dosen_wali` (
  `dsw_id` INT NOT NULL AUTO_INCREMENT,
  `dsw_mahasiswa` INT NOT NULL,
  `dsw_dosen` INT NOT NULL,
  `dsw_status` TINYINT(1) NULL,
  `dsw_created` TIMESTAMP NULL,
  `dsw_updated` TIMESTAMP NULL,
  PRIMARY KEY (`dsw_id`, `dsw_mahasiswa`, `dsw_dosen`),
  INDEX `fk_dosen_wali_mahasiswa_idx` (`dsw_mahasiswa` ASC),
  INDEX `fk_dosen_wali_dosen1_idx` (`dsw_dosen` ASC),
  CONSTRAINT `fk_dosen_wali_mahasiswa`
    FOREIGN KEY (`dsw_mahasiswa`)
    REFERENCES `frs_db`.`mahasiswa` (`mhs_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dosen_wali_dosen1`
    FOREIGN KEY (`dsw_dosen`)
    REFERENCES `frs_db`.`dosen` (`dos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frs_db`.`dosen_departemen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frs_db`.`dosen_departemen` ;

CREATE TABLE IF NOT EXISTS `frs_db`.`dosen_departemen` (
  `dod_id` INT NOT NULL AUTO_INCREMENT,
  `dod_dosen` INT NOT NULL,
  `dod_departemen` INT NOT NULL,
  `dod_status` TINYINT(1) NULL,
  `dod_created` TIMESTAMP NULL,
  `dod_updated` TIMESTAMP NULL,
  PRIMARY KEY (`dod_id`, `dod_dosen`, `dod_departemen`),
  INDEX `fk_dosen_departemen_dosen1_idx` (`dod_dosen` ASC),
  INDEX `fk_dosen_departemen_departemen1_idx` (`dod_departemen` ASC),
  CONSTRAINT `fk_dosen_departemen_dosen1`
    FOREIGN KEY (`dod_dosen`)
    REFERENCES `frs_db`.`dosen` (`dos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dosen_departemen_departemen1`
    FOREIGN KEY (`dod_departemen`)
    REFERENCES `frs_db`.`departemen` (`dep_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frs_db`.`tahun_akademik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frs_db`.`tahun_akademik` ;

CREATE TABLE IF NOT EXISTS `frs_db`.`tahun_akademik` (
  `tak_id` INT NOT NULL AUTO_INCREMENT,
  `tak_tahun` VARCHAR(45) NULL,
  `tak_isganjil` BIT NULL,
  PRIMARY KEY (`tak_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frs_db`.`matakuliah`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frs_db`.`matakuliah` ;

CREATE TABLE IF NOT EXISTS `frs_db`.`matakuliah` (
  `mtk_id` INT NOT NULL AUTO_INCREMENT,
  `mtk_kode` VARCHAR(10) NOT NULL,
  `mtk_tahunakademik` INT NOT NULL,
  `mtk_departemen` INT NULL,
  `mtk_dosen` INT NOT NULL,
  `mtk_nama` VARCHAR(45) NULL,
  `mtk_kelas` CHAR(1) NULL,
  `mtk_sks` INT NULL,
  `mtk_kuota` INT NULL,
  `mtk_status` TINYINT(1) NULL,
  `mtk_created` TIMESTAMP NULL,
  `mtk_updated` TIMESTAMP NULL,
  PRIMARY KEY (`mtk_id`, `mtk_tahunakademik`, `mtk_dosen`),
  UNIQUE INDEX `mtk_kode_UNIQUE` (`mtk_kode` ASC),
  INDEX `fk_matakuliah_departemen1_idx` (`mtk_departemen` ASC),
  INDEX `fk_matakuliah_dosen1_idx` (`mtk_dosen` ASC),
  INDEX `fk_matakuliah_tahun_akademik1_idx` (`mtk_tahunakademik` ASC),
  CONSTRAINT `fk_matakuliah_departemen1`
    FOREIGN KEY (`mtk_departemen`)
    REFERENCES `frs_db`.`departemen` (`dep_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matakuliah_dosen1`
    FOREIGN KEY (`mtk_dosen`)
    REFERENCES `frs_db`.`dosen` (`dos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matakuliah_tahun_akademik1`
    FOREIGN KEY (`mtk_tahunakademik`)
    REFERENCES `frs_db`.`tahun_akademik` (`tak_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frs_db`.`rencana_studi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frs_db`.`rencana_studi` ;

CREATE TABLE IF NOT EXISTS `frs_db`.`rencana_studi` (
  `rst_id` INT NOT NULL AUTO_INCREMENT,
  `rst_matakuliah` INT NOT NULL,
  `rst_mahasiswa` INT NOT NULL,
  `rst_target` CHAR(2) NOT NULL,
  `rst_nilai` CHAR(2) NULL,
  `rst_bobot` FLOAT NULL,
  `rst_point` FLOAT NULL,
  `rst_status` TINYINT(1) NULL,
  `rst_created` TIMESTAMP NULL,
  `rst_updated` TIMESTAMP NULL,
  PRIMARY KEY (`rst_id`, `rst_matakuliah`, `rst_mahasiswa`),
  INDEX `fk_rencana_studi_matakuliah1_idx` (`rst_matakuliah` ASC),
  INDEX `fk_rencana_studi_mahasiswa1_idx` (`rst_mahasiswa` ASC),
  CONSTRAINT `fk_rencana_studi_matakuliah1`
    FOREIGN KEY (`rst_matakuliah`)
    REFERENCES `frs_db`.`matakuliah` (`mtk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rencana_studi_mahasiswa1`
    FOREIGN KEY (`rst_mahasiswa`)
    REFERENCES `frs_db`.`mahasiswa` (`mhs_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frs_db`.`kuota_sks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frs_db`.`kuota_sks` ;

CREATE TABLE IF NOT EXISTS `frs_db`.`kuota_sks` (
  `kts_id` INT NOT NULL AUTO_INCREMENT,
  `kts_tahunakademik` INT NOT NULL,
  `kts_mahasiswa` INT NOT NULL,
  `kts_sks` INT NULL,
  PRIMARY KEY (`kts_id`, `kts_tahunakademik`, `kts_mahasiswa`),
  INDEX `fk_kuota_sks_tahun_akademik1_idx` (`kts_tahunakademik` ASC),
  INDEX `fk_kuota_sks_mahasiswa1_idx` (`kts_mahasiswa` ASC),
  CONSTRAINT `fk_kuota_sks_tahun_akademik1`
    FOREIGN KEY (`kts_tahunakademik`)
    REFERENCES `frs_db`.`tahun_akademik` (`tak_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kuota_sks_mahasiswa1`
    FOREIGN KEY (`kts_mahasiswa`)
    REFERENCES `frs_db`.`mahasiswa` (`mhs_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
